### ISSUE TITLE
nextjs version with ssg and ssr?

### ISSUE THREAD

**Issue by pankaj9296** [ofekashery/react-dashboard-design#3]
This looks so good, thank you. looking forward to use it as a starter for my new saas project.

How can I convert it to a nextjs project?

I know I can just copy the content in pages file, but there are some dependency like 'react-jss', 'react-feature', 'styles-jsx' etc and nextjs already equipped with most them so I'm little confused how should I configure the pages with minimal dependencies.

**Comment by ofekashery** [comment]
Move to #5.
