### ISSUE TITLE
Use Nextjs instead of CRA

### ISSUE THREAD

**Issue by ivanjeremic** [ofekashery/react-dashboard-design#5]
Since this is a Vercel like the dashboard and it uses Ghost-UI a Nextjs example would be nice, I tried to create one but somethow the dark mode toggle does not work, but good job on one hope to see Nextjs to.

**Comment by pankaj9296** [comment]
@ivanjeremic let me know if you are still looking for nextjs version of this.
I was able to convert it to nextjs with working darkmode.

**Comment by ivanjeremic** [comment]
> @ivanjeremic let me know if you are still looking for nextjs version of this.
> I was able to convert it to nextjs with working darkmode.

Yes, that would be nice :)

**Comment by ofekashery** [comment]
Hi there, I just re-wrote the project in Next.js 🎉.
