### ISSUE TITLE
Styling issues after migrating to Create-React-App

### ISSUE THREAD

**Issue by Accretence** [ofekashery/react-dashboard-design#7]
Features like Dark/ Light mode work ( So `GeistProvider`, `CssBaseline` and `PrefersContext` are provided correctly ) but the styling does not transfer correctly. Is there an additional step needed to migrate the application to Create-React-App?

![image](https://user-images.githubusercontent.com/45223699/126882082-dff6b1be-e62d-4bdc-ac28-4399234c42ba.png)

**Comment by ofekashery** [comment]
Hey @Accretence! It's a little hard to answer without seeing the code.
Maybe it's something related to the [``styled-jsx``](https://github.com/vercel/styled-jsx)? You can find your favorite React.js styling method and match the code to it.

**Comment by Accretence** [comment]
Hey @ofekashery! Yes, this is my first time working with this kind of styling method and after some fiddling around I found out that **some of** my selectors in the `<style jsx>` element are not working correctly. For example :

`.submenu__inner :global(.tab) {
          ...
        }`

is not influencing the submenu tabs but:

`.tab {
   ...
}`

does. Is there anyway to make these selector work correctly with CRA?

**Comment by ofekashery** [comment]
@Accretence Yes, the ``:global()``'s are used by [``styled-jsx``](https://github.com/vercel/styled-jsx) only.
If you don't use [``styled-jsx``](https://github.com/vercel/styled-jsx), you should remove them like this:
``.submenu__inner :global(.tab) { ... }`` → ``.submenu__inner .tab { ... }``

**Comment by Accretence** [comment]
Worked like a charm. Thank you for your help and thank you for this amazing resource.❤️
